[package]
name = "semver_bump"
version = "0.1.0"
authors = ["Þórhallur Sverrisson <thorhallur.sverrisson@rb.is>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
semver = "0.11.0"
